DROP DATABASE IF EXISTS usersdb;

CREATE DATABASE usersdb;

USE usersdb;

CREATE TABLE Users
(
	id INT NOT NULL AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    PRIMARY KEY(id)
) AUTO_INCREMENT = 1;

CREATE TABLE Notes
(
    id INT NOT NULL AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    messageText VARCHAR(255) NOT NULL,
    favorite BOOLEAN NOT NULL DEFAULT FALSE,
    authorId INT NOT NULL,
    writingDate VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (authorId) REFERENCES Users(id) ON DELETE CASCADE
) AUTO_INCREMENT = 1;